-- À exécuter dans Supabase > SQL Editor.

create table if not exists public.user_budget_data (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  storage_key text not null,
  payload jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (user_id, storage_key)
);

alter table public.user_budget_data enable row level security;

create policy "Users can read their own budget"
on public.user_budget_data
for select
to authenticated
using (auth.uid() = user_id);

create policy "Users can insert their own budget"
on public.user_budget_data
for insert
to authenticated
with check (auth.uid() = user_id);

create policy "Users can update their own budget"
on public.user_budget_data
for update
to authenticated
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

create policy "Users can delete their own budget"
on public.user_budget_data
for delete
to authenticated
using (auth.uid() = user_id);

create or replace function public.set_updated_at()
returns trigger
language plpgsql
security invoker
set search_path = public
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists set_user_budget_data_updated_at on public.user_budget_data;
create trigger set_user_budget_data_updated_at
before update on public.user_budget_data
for each row execute function public.set_updated_at();
